name: CI

# Controls when the action will run. Triggers the workflow on push or pull request events
on:
  push:
    branches: [ master,piyush-deploy-main ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Zip Release
      uses: TheDoctor0/zip-release@v0.3.0
      with:
        # Filename for archive
        filename: release.zip
        # Base path for archive files
        path: .
        # Working directory before zipping
        directory: .
        exclusions: .git
    
    - name: Beanstalk Deploy
      uses: einaregilsson/beanstalk-deploy@v9
      with:
        aws_access_key: ${{ secrets.aws_access_key }}
        aws_secret_key: ${{ secrets.aws_secret_key }}
        region: ap-south-1
        application_name: php-mode
        environment_name: PhpMode-env
        version_label: ${{ github.sha }}
        deployment_package: release.zip
