name: Dev CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Zip Release
      uses: TheDoctor0/zip-release@v0.3.0
      with:
        filename: release.zip
        # Base path for archive files
        path: .
        # Working directory before zipping
        directory: .
        exclusions: .git
    
    - name: Beanstalk Deploy
      uses: einaregilsson/beanstalk-deploy@v9
      with:
        aws_access_key: ${{ secrets.aws_access_key }}
        aws_secret_key: ${{ secrets.aws_secret_key }}
        region: ap-south-1
        application_name: iitb-act-frontend-dev-app
        environment_name: iitb-act-frontend-dev-env-v2
        version_label: ${{ github.sha }}
        deployment_package: release.zip
